### PR TITLE
Add perf and nvidia-smi to blog post

### PR DESCRIPTION
**Pull request by stefanos1316**
Please let me know if anything is needed to be changed, even if it is very minor.

### CODE REVIEW

**Comment by luiscruz** [comment]
Stefano,
A few minor things:
- There are two more references to the total number of tools: Section "Deciding on a suitable energy profiler" and section "Wrap-up". Please change it from 4 to 6, four to six.
- We need to update the decision graph.

Let me know if you agree with this one:

https://mermaid.live/edit#eyJjb2RlIjoiZ3JhcGggVERcbkFbV2hpY2ggRW5lcmd5IFByb2ZpbGVyIHNob3VsZCBJIHVzZT9dIC0tPiBDe09TP31cbkMgLS0-fE1hY3wgRHtDb21mb3J0YWJsZSB3aXRoPGJyLz4gdGhlIGNvbW1hbmQtbGluZT99XG5EIC0tPnxZZXN8IERZW0ludGVsIFBvd2VyTG9nXVxuRCAtLT58Tm98IEROW1Bvd2VyIEdhZGdldF1cbkMgLS0-fExpbnV4fCBDQXtTb2Z0d2FyZSB1c2luZyBOdmlkaWEgR1BVP31cbkNBIC0tPnxOb3wgRXtQcm9jZXNzb3I_fVxuRSAtLT58SW50ZWx8IEZbUG93ZXJzdGF0LCBQb3dlclRPUCwgb3IgUGVyZl1cbkUgLS0-fEFNRHwgUG93ZXJUT1BcbkNBIC0tPnxZZXN8IE52aWRpYS1zbWlcbkMgLS0-fFdpbmRvd3N8IEQiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ

If you agree with it, please copy/paste the mermaid markup.

**Comment by stefanos1316** [comment]
Hi Luis,

Updated and resubmitted.
Yes I do agree, but please note that `nvidia-smi` can also be used on Windows as far as I know.
However, I have never tried it on Windows and the blog shows how to use it on Linux.
Should we leave the graph as you suggested?

**Comment by luiscruz** [comment]
Let's leave the graph as is for now. I will think about it and change it if needed. Thanks, Stefanos!

**Comment by stefanos1316** [comment]
You are welcome Luis.
If I have any new tools in mind then I will update the blog :)

**Pull request merged**
